version: 2.1

orbs:
  docker: circleci/docker@1.0.1

jobs:
  compute-version:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Compute a version designator and write it to a text file
          command: echo "0.0.${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1:0:7}" | tee version.txt
      - persist_to_workspace:
          root: ./
          paths:
            - ./

  install-dependencies:
    docker:
      - image: node:current-alpine
    steps:
      - attach_workspace:
          at: ./
      - restore_cache:
          keys:
            - yarn-deps-{{ checksum "yarn.lock" }}
            - yarn-deps
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-deps-{{ checksum "yarn.lock" }}
      - store_artifacts:
          path: yarn.lock
      - persist_to_workspace:
          root: ./
          paths:
            - ./

  build-production:
    docker:
      - image: node:current-alpine
    steps:
      - run:
          name: Install bash
          command: apk add bash
      - attach_workspace:
          at: ./
      - run:
          name: Setup __BUILD_VERSION envvar
          command: echo "export __BUILD_VERSION=$(cat version.txt)" >> $BASH_ENV
      - run:
          name: Production build
          command: yarn build
          shell: bash -eo pipefail
      - store_artifacts:
          path: dist/server.js
      - setup_remote_docker:
          docker_layer_caching: true
      - docker/check
      - docker/build:
          image: makotom/decode-server-preview
          tag: $__BUILD_VERSION
          shell: bash -eo pipefail
      - docker/push:
          image: makotom/decode-server-preview
          digest-path: digest.txt
      - run:
          name: Show Docker image digest
          command: cat digest.txt

  test:
    docker:
      - image: node:current-alpine
    parallelism: 2
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Run tests
          command: |
            circleci tests glob '**/*.test.ts' | circleci tests split --split-by timings | xargs yarn test:ci
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - compute-version
      - install-dependencies:
          requires:
            - compute-version
      - build-production:
          context: docker-hub
          requires:
            - install-dependencies
      - test:
          requires:
            - install-dependencies
      - deploy-approval:
          type: approval
          requires:
            - build-production
            - test
